global:
  evaluation_interval: 30s
  scrape_interval: 5s
storage:
  tsdb:
    out_of_order_time_window: 30m
scrape_configs:
- job_name: otel-collector
  static_configs:
  - targets:
    - 'otelcol:8888'
- job_name: buyer
  static_configs:
  - targets:
    - 'buyer:3001'
- job_name: factory
  static_configs:
  - targets:
    - 'factory:3003'
